server:
  port: 8001

spring:
  profiles:
    active: dev
  jackson:
    time-zone: GMT+8
  data:
    redis:
      repositories:
        enabled: false
  activiti:
    check-process-definitions: false  
  resources:
    static-locations: classpath:/static
  mvc:
    static-path-pattern: /static/**

  redis:
    #数据库索引
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    #连接超时时间
    timeout: 5000

#七牛云
qiniu:
  # 文件大小 /M
  max-size: 15

#邮箱验证码有效时间/分钟
code:
  expiration: 5

#登录图形验证码有效时间/分钟
loginCode:
  expiration: 2

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: ['com.taiji.cloudmp.domain','com.taiji.cloudmp.mhpt.modules.system.domain']
  mapper-locations: classpath*:mybatis/mapper/*/*/*Mapper.xml
logging:
  level:
    com.taiji.cloudmp.mhpt.modules.system.repository: debug  
    com.taiji.cloudmp.repository: debug